-- Active: 1725863081635@@127.0.0.1@5433@todo_stack_db@public
-- Generated by the database client.
drop table users;

CREATE TABLE users(
    id SERIAL NOT NULL,
    email varchar(89) NOT NULL,
    nickname varchar(10) NOT NULL,
    password varchar(255) NOT NULL,
    last_password_changed timestamp without time zone NOT NULL,
    tel_number varchar(20),
    address varchar(255),
    address_detail varchar(255),
    profile_image_url text,
    is_oauth boolean NOT NULL,
    is_email_verified boolean NOT NULL DEFAULT false,
    email_verified_token varchar(64),
    email_verified_token_expire_at timestamp without time zone,
    created_date timestamp without time zone NOT NULL,
    updated_date timestamp without time zone NOT NULL,
  	refresh_token varchar(255),
    PRIMARY KEY(id)
);



COMMENT ON TABLE users IS '유저의 정보';
COMMENT ON COLUMN users.email IS '이메일';
COMMENT ON COLUMN users.nickname IS '닉네임';
COMMENT ON COLUMN users.password IS '비밀번호';
COMMENT ON COLUMN users.last_password_changed IS '최근 비밀변호 변경 시점';
COMMENT ON COLUMN users.tel_number IS '전화번호';
COMMENT ON COLUMN users.address IS '주소';
COMMENT ON COLUMN users.address_detail IS '주소의 상세정보';
COMMENT ON COLUMN users.profile_image_url IS '프로필 이미지의 url';
COMMENT ON COLUMN users.is_oauth IS '소셜 로그인 이용 여부';
COMMENT ON COLUMN users.is_email_verified IS '일반 로그인시 이메일 인증 여부';
COMMENT ON COLUMN users.created_date IS '계정 생성 시점';
COMMENT ON COLUMN users.updated_date IS '프로필 정보 변경 시점';
COMMENT ON COLUMN users.refresh_token IS '리프레시 토큰';


-- 유저 데이터 삽입
INSERT INTO users (email, nickname, password, last_password_changed, tel_number, address, address_detail, profile_image_url, is_oauth, is_email_verified, created_date, updated_date, refresh_token)
VALUES 
('user1@example.com', 'user1', 'hashedpassword1', NOW(), '010-1234-5678', '123 Main St', 'Apt 101', 'http://example.com/profile1.jpg', false, true, NOW(), NOW(), 'refreshToken1'),
('user2@example.com', 'user2', 'hashedpassword2', NOW(), '010-2345-6789', '456 Side St', 'Suite 202', 'http://example.com/profile2.jpg', true, true, NOW(), NOW(), 'refreshToken2'),
('user3@example.com', 'user3', 'hashedpassword3', NOW(), '010-3456-7890', '789 Back St', 'Room 303', 'http://example.com/profile3.jpg', false, false, NOW(), NOW(), 'refreshToken3');


-- 이메일 인증 테이블

delete from users where id = 8;